// The event types and their payload schema versions (design.md "Events"), apart from types.ts for its size.
// Wire type is the dotted form; the glossary carries the domain name (JobQueued, ...).

export const EVENT_TYPES = [
  'job.queued', 'job.prioritized', 'job.held', 'job.approved', 'job.claimed', 'job.started',
  'job.progressed', 'job.finished', 'job.failed', 'job.cancelled', 'job.requeued', 'job.reattached', 'job.reprioritized', 'job.respecified',
  'lane.opened', 'lane.closed', 'decision.made',
  'question.asked', 'question.escalated', 'question.escalated_to_human', 'question.answered', 'question.closed', 'question.dismissed', 'question.expired', 'question.lapsed',
  'update.available', 'update.started', 'update.applied', 'update.failed', 'plugin.installed', 'plugin.removed',
  'job.accepted', 'job.rejected', 'queue.ordered', 'queue.gate_changed', 'job.claimed_by_operator',
  'job.rerun', 'job.dismissed', 'job.unassigned', 'job.reassigned', 'job.work_kept', 'job.work_removed', 'job.cleanup_deferred', 'job.cleaned_up',
  'job.parked', 'job.unparked', 'job.continued', 'job.waiting', 'job.wait_ended',
  'source.stalled', 'connected_account.expired', 'connected_account.renewed', 'connected_account.renewal_failed', 'ui_session.ended', 'source.claim_released', 'source.intake_migrated', 'source.issues_assigned',
  'auth.pending', 'auth.completed', 'auth.expired', 'auth.cancelled', 'auth.failed',
  'job.assessed', 'failure.grouped', 'failure.resolved', 'failure.released', 'handoff.opened', 'handoff.closed', 'handoff.checked',
  'usage.limits_changed', 'priority_lanes.changed', 'priority_lanes.settings_changed',
  'proposal.asked', 'proposal.submitted', 'proposal.escalated', 'proposal.escalated_to_human', 'proposal.reviewed',
  'proposal.revision_requested', 'proposal.accepted', 'proposal.rejected', 'proposal.cancelled', 'proposal.followed_on',
  'research.asked', 'research.submitted', 'research.escalated', 'research.escalated_to_human', 'research.reviewed',
  'research.revision_requested', 'research.accepted', 'research.cancelled',
  'machine.discovered', 'machine.discovery_failed', 'machine.radius_grew', 'machine.actor_mismatch', 'blast_radius.settings_changed', 'job.gate_passed',
  'minor_decision.picked', 'minor_decision.compared', 'minor_decision.overridden', 'minor_decision.settings_changed',
  'job.phase_changed', 'job.forked', 'job.fork_resolved', 'phase_shifts.settings_changed',
  'question.corrected', 'auto_answer.settings_changed', 'auto_park.settings_changed',
  'github_proxy.done', 'github_proxy.refused', 'github_proxy.failed',
  'vault.secret_set', 'vault.secret_removed', 'vault.secret_read', 'vault.secret_migrated', 'template.saved', 'template.removed', 'vault.approved', 'vault.revoked', 'template.profile_approved', 'vault.delivered', 'vault.refused', 'vault.minted', 'vault.mint_refused',
  'vault.credential_asked', 'vault.credential_given', 'vault.credential_declined',
  'yolo_mode.changed', 'job.pull_request_merged', 'job.pull_request_closed', 'job.finish_briefed',
  'skill.listed', 'skill.loaded', 'skill.refused',
  'artifact.created', 'artifact.shared', 'artifact.share_revoked', 'artifact.removed', 'artifact.settings_changed', 'artifact.posted',
  'tldr.written', 'tldr.settings_changed',
  'item.snapshot_recorded', 'item.changed_since_snapshot', 'item.original_kept', 'item.new_text_accepted',
] as const;
export type EventType = typeof EVENT_TYPES[number];

/**
 * Payload schema version per event type (docs/schemas/<type>.v<N>.json). Additive field →
 * same version; removed/renamed/retyped field → bump. The store stamps it on append.
 */
export const EVENT_SCHEMA_VERSIONS: Readonly<Record<EventType, number>> = {
  'job.queued': 1, 'job.prioritized': 3, 'job.held': 1, 'job.approved': 1, 'job.claimed': 1,
  'job.started': 1, 'job.progressed': 1, 'job.finished': 1, 'job.failed': 1, 'job.cancelled': 1,
  'job.requeued': 1, 'job.reattached': 1, 'job.reprioritized': 1, 'job.respecified': 1, 'lane.opened': 1, 'lane.closed': 1,
  'decision.made': 3, 'question.asked': 1, 'question.escalated': 2, 'question.escalated_to_human': 1,
  'question.answered': 2, 'question.closed': 1, 'question.dismissed': 1, 'question.expired': 1, 'question.lapsed': 1,
  'update.available': 1, 'update.started': 1, 'update.applied': 1, 'update.failed': 1, 'plugin.installed': 1, 'plugin.removed': 1,
  'job.accepted': 1, 'job.rejected': 1, 'queue.ordered': 1, 'queue.gate_changed': 1, 'job.claimed_by_operator': 1,
  'job.rerun': 1, 'job.dismissed': 1, 'job.unassigned': 1, 'job.reassigned': 1, 'job.work_kept': 1, 'job.work_removed': 1, 'job.cleanup_deferred': 1, 'job.cleaned_up': 1,
  'job.parked': 1, 'job.unparked': 1, 'job.continued': 1, 'job.waiting': 1, 'job.wait_ended': 1,
  'source.stalled': 1, 'connected_account.expired': 1, 'connected_account.renewed': 1, 'connected_account.renewal_failed': 1, 'ui_session.ended': 1,
  'source.claim_released': 1, 'source.intake_migrated': 1, 'source.issues_assigned': 1,
  'auth.pending': 1, 'auth.completed': 1, 'auth.expired': 1, 'auth.cancelled': 1, 'auth.failed': 1,
  'job.assessed': 1, 'failure.grouped': 1, 'failure.resolved': 1, 'failure.released': 1, 'handoff.opened': 1, 'handoff.closed': 1, 'handoff.checked': 1,
  'usage.limits_changed': 1, 'priority_lanes.changed': 1, 'priority_lanes.settings_changed': 1,
  'proposal.asked': 1, 'proposal.submitted': 2, 'proposal.escalated': 2, 'proposal.escalated_to_human': 1, 'proposal.reviewed': 1,
  'proposal.revision_requested': 1, 'proposal.accepted': 1, 'proposal.rejected': 1, 'proposal.cancelled': 1, 'proposal.followed_on': 1,
  'research.asked': 1, 'research.submitted': 1, 'research.escalated': 1, 'research.escalated_to_human': 1, 'research.reviewed': 1,
  'research.revision_requested': 1, 'research.accepted': 1, 'research.cancelled': 1,
  'machine.discovered': 1, 'machine.discovery_failed': 1, 'machine.radius_grew': 1, 'machine.actor_mismatch': 1, 'blast_radius.settings_changed': 1, 'job.gate_passed': 1,
  'minor_decision.picked': 1, 'minor_decision.compared': 1, 'minor_decision.overridden': 1, 'minor_decision.settings_changed': 1,
  'job.phase_changed': 1, 'job.forked': 1, 'job.fork_resolved': 1, 'phase_shifts.settings_changed': 1,
  'question.corrected': 1, 'auto_answer.settings_changed': 1, 'auto_park.settings_changed': 1,
  'github_proxy.done': 1, 'github_proxy.refused': 1, 'github_proxy.failed': 1,
  'vault.secret_set': 1, 'vault.secret_removed': 1, 'vault.secret_read': 1, 'vault.secret_migrated': 1, 'template.saved': 1, 'template.removed': 1, 'vault.approved': 1, 'vault.revoked': 1, 'template.profile_approved': 1, 'vault.delivered': 1, 'vault.refused': 1, 'vault.minted': 1, 'vault.mint_refused': 1,
  'vault.credential_asked': 1, 'vault.credential_given': 1, 'vault.credential_declined': 1,
  'yolo_mode.changed': 1, 'job.pull_request_merged': 1, 'job.pull_request_closed': 1, 'job.finish_briefed': 1,
  'skill.listed': 1, 'skill.loaded': 1, 'skill.refused': 1,
  'artifact.created': 1, 'artifact.shared': 1, 'artifact.share_revoked': 1, 'artifact.removed': 1, 'artifact.settings_changed': 1, 'artifact.posted': 1,
  'tldr.written': 1, 'tldr.settings_changed': 1,
  'item.snapshot_recorded': 1, 'item.changed_since_snapshot': 1, 'item.original_kept': 1, 'item.new_text_accepted': 1,
};
