// The API reference (issue #68, design.md "API reference"): an OpenAPI 3.1 document of every route
// under /api/ and /ui/. Parameters and request bodies are the zod schemas the routes parse with,
// turned into JSON Schema, so they cannot drift; summaries and answers are written here. The daemon
// refuses to start when a route and this document disagree (`referenceDrift`, checked on ready).
import { z } from 'zod';
import { ENVELOPE_SCHEMA } from '../events/index.ts';
import { REVIEW_KINDS, REVIEW_SECTIONS, SECTIONS, type ReviewKind, type UiRole } from '../domain/types.ts';
import { jobsQuery } from './jobs.ts';
import { loginsQuery } from './logins.ts';
import { questionsQuery } from './questions.ts';
import { loginSettingsBody } from './ui/logins.ts';
import { priorityLaneSettingsBody } from './ui/priority-lanes.ts';
import { blastRadiusSettingsBody, discoverBody } from './ui/blast-radius.ts';
import { failureCauseBody, failureForgetBody, failureSettingsBody, handoffResolveBody } from './ui/failures.ts';
import { decisionPointBody, overrideBody } from './ui/minor-decisions.ts';
import { streamQuery } from './sse.ts';
import { decisionsQuery, eventsQuery } from './state.ts';
import { SESSION_HEADER } from './ui/guard.ts';
import {
  connectedAccountsBody, historyRetentionBody, usageGraphViewBody, usageLimitsBody, deviceLinkBody, queueGateBody, queueOrderBody, machineDefaultsBody, machineHostKeyBody, machinesEditBody, pluginStoreBody, pluginsEditBody, realmsEditBody, routingEditBody, rulesBody, jobRulesBody, updateBody, usersEditBody,
  machineJoinBody,
} from './ui/index.ts';
import { answerBody, intakeActionBody, rejectBody, requeueBody } from './ui/job-bodies.ts';
import { notifierActionBody, webhookTestBody, webhooksEditBody } from './ui/webhooks-notifiers.ts';
import { vaultEditBody } from './ui/vault.ts';
import { completeBody, devicePollBody, deviceStartBody, loginBody, passwordBody, startQuery } from './ui/sign-in.ts';
import { reviewQuery } from './reviews.ts';
import { acceptBody, notesBody, optionalNotesBody, reviewSettingsBody } from './ui/reviews.ts';
import { phaseShiftSettingsBody, shiftBody } from './ui/phase-shifts.ts';
import { deliveriesQuery } from './webhooks.ts';
import { accessEditBody } from './ui/access.ts';
import { usageHistoryQuery } from './usage-history.ts';

type Tag = 'State' | 'Jobs' | 'Questions' | 'Proposals' | 'Research' | 'Logins' | 'Failures' | 'Minor decisions' | 'Machines and usage' | 'Plugins and routing' | 'Webhooks' | 'Vault' | 'Events' | 'Self-update' | 'Users' | 'Sign-in' | 'Access';

interface Operation {
  method: 'get' | 'post';
  /** Fastify's form: `/api/jobs/:id`. */
  path: string;
  tag: Tag;
  summary: string;
  description?: string;
  query?: z.ZodObject;
  body?: z.ZodType;
  /** Body media type; default JSON. */
  form?: boolean;
  /** What a 200 carries. */
  returns: string;
  /** Answer media type; default JSON. */
  answers?: 'html' | 'sse' | 'xml' | 'redirect';
  /** A UI mutation: the least UI role that may make it. */
  role?: UiRole;
  /** Error statuses beyond the guards'. */
  errors?: number[];
}

const id = (what: string) => ({ name: 'id', in: 'path', required: true, description: `the ${what}'s id`, schema: { type: 'string' } });
const name = { name: 'name', in: 'path', required: true, description: 'the realm, as the sign-in config names it', schema: { type: 'string' } };

/** A review section's routes (issues #537, #543), the same for every one: built from its type, so none is left out. */
function reviewOperations(kind: ReviewKind): Operation[] {
  const t = REVIEW_SECTIONS[kind];
  const tag = SECTIONS[t.section].label as Tag;
  const view = '`ReviewItemView`';
  const parts = t.parts.map((p) => p.id).join(', ');
  return [
    { method: 'get', path: `/api/${t.section}`, tag, summary: `List ${t.noun}s, with the ${t.section} settings and the section's type`, description: `A ${t.noun} is what a job asked for one wrote instead of doing the work, ended with ${t.marker}: its versions (each with its parts — ${parts} — and the parts it left out), its review trail (each reviewer level's verdict and notes, and a person's decisions), and its sign-off (who, when, which version). \`status\` \`open\` (the default): in review or sent back, high-priority jobs' first, then oldest first; any other is a history, newest first. \`settings\`: the reviewer levels, who may sign off, how often the levels may send one back, and \`levels\`, the escalation levels that may review. \`type\`: the parts and the decisions the server takes.`, query: reviewQuery, returns: '`{ items: ReviewItemView[], settings: ReviewSettingsView, type: ReviewSectionView }`' },
    { method: 'get', path: `/api/${t.section}/:id`, tag, summary: `One ${t.noun}, with its versions and review trail`, returns: view, errors: [404] },
    ...t.decisions.map((d): Operation => ({
      method: 'post', path: `/ui/api/${t.section}/:id/${d.route}`, tag, summary: `${d.label}: a person's decision on a ${t.noun}`,
      description: `${d.effect === 'accept' ? `Signed off accepted (\`${t.prefix}.accepted\`). A job that also asks for a later section is re-queued to write it, in the same session; any other ends finished, the decision its result.` : d.effect === 'reject' ? `Signed off rejected (\`${t.prefix}.rejected\`). Its job ends finished, the decision its result.` : `Sent back (\`${t.prefix}.revision_requested\`, \`decision\` \`${d.id}\`): its job is re-queued with \`notes\`, in the same session, and its next ${t.noun} is the next version, reviewed from the first reviewer level again.`} \`notes\` ${d.notes === 'required' ? 'is required' : 'is optional'}. Over any reviewer level in flight.${d.effect === 'accept' ? ' `then` (issue #548): only while its job is in a phase a question switched it to — the item\'s `then` lists the choices —: `work` the job goes back to the work with it as context, `end` it ends finished, `proposal` (research only) it writes a proposal next, in the same session. Rejected, a switched job goes back to work, told so.' : ''} 409: it is not open${d.effect === 'accept' ? ', or `then` is not one of its choices' : ''}.`,
      role: 'operator', body: d.effect === 'accept' ? acceptBody : d.notes === 'required' ? notesBody : optionalNotesBody, returns: `the ${view}`, errors: [404, 409],
    })),
    { method: 'post', path: `/ui/api/${t.section}/:id/seen`, tag, summary: `Mark a ${t.noun} seen`, role: 'operator', returns: `the ${view}`, errors: [404] },
    { method: 'post', path: `/ui/api/jobs/:id/${t.askPath}`, tag, summary: `Ask a job that has not started for a ${t.noun}`, description: `When it starts, its agent is told to write one instead of doing the work (\`spec.${t.specFlag}\`, \`${t.prefix}.asked\`). An item labelled \`${t.label}\`, or with a ${SECTIONS[t.section].label} heading in its body, asks it from the start. 409: the job has started.`, role: 'operator', returns: 'the `Job`', errors: [404, 409] },
    { method: 'post', path: `/ui/api/${t.section}/settings`, tag, summary: `Change the ${t.section} settings`, description: 'Any part; one left out keeps its value. `reviewers`: the escalation levels that review, lowest first, by name (none, the default: a person reviews). `signOff` `owner` (the default): only a person accepts; `top-level`: the top reviewer level\'s approval accepts too. `levelRevisions` (0 to 5, default 1): how often the reviewer levels may send one back before a person decides. Applies to the next review, without a restart. 400: a reviewer that is not an escalation level now.', role: 'admin', body: reviewSettingsBody, returns: '`ReviewSettingsView`', errors: [400] },
  ];
}

const OPERATIONS: Operation[] = [
  { method: 'get', path: '/api/health', tag: 'State', summary: 'Health and version', description: 'A loopback read without a session on a hopper with several users reads the instance\'s part only: `{ ok, version, uptimeS }`.', returns: '`{ ok, version, router, fallback, executors, parkingExecutors, reviewingExecutors, uptimeS }`: `parkingExecutors` the executors that can park a job; `reviewingExecutors` the ones that write research reports and proposals (only their jobs shift phase from a question)' },
  { method: 'get', path: '/api/queue', tag: 'State', summary: 'The queue', returns: '`{ waiting, running, waitingAnswer, operatorLed, parked, locked, ended, gate, presort }`: each list a `Job[]`, `waiting` in queue order (the user order first), `locked` the locked entries (failed jobs kept in the queue until run again or dismissed), highest priority first, `ended` the last 24 h; `gate` the `QueueGate`; `presort` the `PreSort` of the waiting jobs not yet accepted' },
  { method: 'get', path: '/api/decisions', tag: 'State', summary: 'Recent decisions', query: decisionsQuery, returns: '`{ decisions: Decision[] }`, newest first' },
  { method: 'get', path: '/api/decisions/:id', tag: 'State', summary: 'One decision', returns: '`Decision`', errors: [404] },
  { method: 'get', path: '/api/router', tag: 'State', summary: 'Router status', returns: '`{ router, plugin, fallback, reason? }`' },
  { method: 'get', path: '/api/accounts', tag: 'State', summary: 'Who each part acts as', description: 'Each usage source\'s and job source\'s account on an outside service. Never a token.', returns: '`{ accounts: PartAccount[] }`' },
  { method: 'get', path: '/api/sources', tag: 'Jobs', summary: 'Job sources and their sync status', description: 'A GitHub source\'s `detail.intake` lists every open labelled issue it listed: taken (with its `jobId`), or the one `reason` it was not, and the `action` the user can take (`assign`, `release`). `detail.intakeMigration` is what the intake migration changed, once; `detail.outsideRepos` the repos outside the job repositories with open labelled issues assigned to the account.', returns: '`{ sources: SourceStatus[] }`' },
  { method: 'post', path: '/ui/api/sources/:name/intake', tag: 'Jobs', summary: 'Assign issues to me, or release claims, from Sources', description: '`assign`: the labelled issues not assigned to the user are assigned to the connected account (a GitHub write the user makes). `release`: a `hopper:claimed` no job here holds goes, with its holder label. Only items the source\'s last sync offered that action for; the others are answered in `failed`. The source syncs at once, so the assigned or released issues are taken.', role: 'operator', body: intakeActionBody, returns: '`{ done: string[], failed: Record<string, string> }`', errors: [404, 409] },
  { method: 'get', path: '/api/connected-accounts', tag: 'Jobs', summary: 'The GitHub account you connected', description: 'Per provider: connected (the account, when, its scopes, the job repositories), not connected, expired (connect again), unreadable (sealed under a token key the runtime does not give: give it back, as HOPPER_TOKEN_KEY or HOPPER_TOKEN_KEY_PREVIOUS), failed, or waiting with the device code to approve. Facts only, never a token.', returns: '`{ accounts: ConnectedAccountStatus[] }`' },
  { method: 'post', path: '/ui/api/connected-accounts', tag: 'Jobs', summary: 'Connect GitHub, cancel, disconnect, or choose its job repositories', description: '`connect` runs the provider\'s device flow through the hopper\'s app (its public client id, no secret) and answers once it shows the device code; a waiting one answers its own code. Once approved, the account\'s issues in its job repositories become jobs, and the jobs act through it. Signing in with GitHub connects it too. `choose` sets the job repositories, the whole list (none: no job); the source syncs at once. `disconnect` revokes the account\'s grant at GitHub (best effort), forgets the account and its token, and keeps the job repositories. A connect over a live connection revokes the grant it replaces.', role: 'admin', body: connectedAccountsBody, returns: '`ConnectedAccountStatus`' },
  { method: 'get', path: '/api/jobs', tag: 'Jobs', summary: 'List jobs', description: 'Jobs come only from job sources; no route creates one.', query: jobsQuery, returns: '`{ jobs: Job[] }`, newest first' },
  { method: 'get', path: '/api/jobs/:id', tag: 'Jobs', summary: 'One job', returns: '`Job`', errors: [404] },
  { method: 'post', path: '/ui/api/jobs/:id/cancel', tag: 'Jobs', summary: 'Cancel a job', role: 'operator', returns: 'the `Job`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/jobs/:id/approve', tag: 'Jobs', summary: 'Approve a held job', role: 'operator', returns: 'the `Job`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/jobs/:id/operator-led', tag: 'Jobs', summary: 'Claim a waiting job as operator-led', description: 'The job\'s work is done by hand — in an IDE or a terminal — not by an executor: it holds no lane and is never run. It is finished when its source finds the work complete (on GitHub, its closing pull request reached the completion), and cancelled as any job is.', role: 'operator', returns: 'the `Job`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/jobs/:id/reject', tag: 'Jobs', summary: 'Reject a waiting job', description: 'The job ends `rejected`: kept, never run, with the optional `reason` as its error and in its timeline (none: `rejected by the user`). Its source is told; a GitHub issue is left as it is (no label, no comment, never closed) and is not taken again until it is assigned to the user again or run again.', role: 'operator', body: rejectBody, returns: 'the `Job`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/jobs/:id/rerun', tag: 'Jobs', summary: 'Run a failed, finished or rejected job again', description: 'Its source gives the item back (on GitHub: a closed issue is reopened, the end labels go) and a new job for it is queued at once, through routing rules and the queue gate, its `rerunOf` the ended job; the ended job is kept. Only the newest job of its item, once its end was reported to the source; 409 otherwise, or when its source cannot run an item again. 502: the source could not give the item back.', role: 'operator', returns: 'the new `Job`', errors: [404, 409, 502] },
  { method: 'post', path: '/ui/api/jobs/:id/cleaned-up', tag: 'Jobs', summary: 'Mark a deferred cleanup done', description: 'The ended job\'s cleanup could not reach its machine (`cleanupDeferred`), so it is tried again on every tick and a waiting job of the same item is held. Use this once its pane is closed by hand, or its machine is gone for good: `cleanupDeferred` goes, `job.cleaned_up { by: "user" }` is recorded, and the item\'s jobs may run. 409: no deferred cleanup, or one being tried now.', role: 'operator', returns: 'the `Job`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/jobs/:id/park', tag: 'Jobs', summary: 'Park a running job, or one on a question', description: 'The job leaves its lane at once and holds none (`parked`): its pane and agent end, and its work tree, branch, agent session (`agentSession`), machine (`resumeOn`) and open question are kept, for days or weeks. Its question stays answerable and never expires while it is parked; an answer is kept until it is re-queued. A running job is interrupted mid-turn: the answer is the job before it stepped aside. A job whose executor recorded no agent session is parked too; its re-queue then starts a fresh one. 409: the job is not running or on a question, or its executor cannot park (it is not in `parkingExecutors` of GET /api/health).', role: 'operator', returns: 'the `Job`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/jobs/:id/requeue', tag: 'Jobs', summary: 'Re-queue a parked job', description: 'The job waits again, pinned to the machine it ran on (held while that machine is offline, with the reason); its claim opens a new pane in its kept work tree and resumes its agent session there (`claude --resume`), with the answer given while it was parked, if any. With its question still open, it waits on the question again (`waiting_answer`), and the human timeout starts again. A job with no agent session (`agentSession` absent) is re-queued only with `freshSession: true`, the person\'s confirmation: its claim starts a fresh agent session in its kept work tree, told its task, its question and the answer. 409: the job is not parked, or it has no agent session and `freshSession` is not true.', role: 'operator', body: requeueBody, returns: 'the `Job`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/jobs/:id/dismiss', tag: 'Jobs', summary: 'Dismiss a locked entry', description: 'The failed job leaves the queue\'s locked entries (`dismissedAt`); it stays failed, its issue keeps `hopper:failed`, and it can still be run again.', role: 'operator', returns: 'the `Job`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/queue/order', tag: 'Jobs', summary: 'Order the queue', description: 'The user order: these waiting jobs, first to last, run before every other. A job not yet accepted is accepted; a waiting job ranked before and not named loses its rank.', role: 'operator', body: queueOrderBody, returns: '`{ jobs: Job[] }`', errors: [409] },
  { method: 'post', path: '/ui/api/queue/accept-presort', tag: 'Jobs', summary: 'Accept the pre-sort', description: 'Every waiting job not yet accepted: rejected when the pre-sort rejects it, else accepted, in its order.', role: 'operator', returns: '`{ presort: PreSort }`, as it was applied' },
  { method: 'post', path: '/ui/api/queue-gate', tag: 'Jobs', summary: 'Set the queue gate', description: '`auto-accept`: the pre-sort is applied as jobs arrive, at most `autoAcceptPerHour` an hour (null: no limit). `review`: each job waits for the user.', role: 'admin', body: queueGateBody, returns: '`{ gate: QueueGate }`' },
  { method: 'get', path: '/api/job-rules', tag: 'Jobs', summary: 'The job rules', description: 'What every job\'s prompt carries before its work tree and the protocol: the saved text, or the default while none is saved (`missing`), with the default and the fixed lines.', returns: '`JobRulesView`' },
  { method: 'post', path: '/ui/api/job-rules', tag: 'Jobs', summary: 'Replace the job rules', description: '`version` is the one read from GET /api/job-rules. The next job to start gets them.', role: 'admin', body: jobRulesBody, returns: 'the new job rules view', errors: [409] },
  { method: 'get', path: '/api/questions', tag: 'Questions', summary: 'List questions', query: questionsQuery, description: 'Each is a `QuestionView`: its job\'s live priority, the phase shifts an open one offers now (`shifts`, issue #548), and the forks made from it (`forks`, issue #570): each fork\'s job, kind, note, job status, whether it still runs, and its review item and status once it wrote one.', returns: '`{ questions: QuestionView[] }`' },
  { method: 'get', path: '/api/questions/:id', tag: 'Questions', summary: 'One question, with its escalation trail and the machine that raised it', returns: '`QuestionView`', errors: [404] },
  { method: 'get', path: '/api/question-gates', tag: 'Questions', summary: 'The rules and the risk rules', returns: '`QuestionGatesView`' },
  { method: 'post', path: '/ui/api/questions/:id/answer', tag: 'Questions', summary: 'Answer an open question', role: 'operator', body: answerBody, returns: 'the `Question`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/questions/:id/close', tag: 'Questions', summary: 'Close an open question', role: 'operator', returns: 'the `Question`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/questions/:id/dismiss', tag: 'Questions', summary: 'Dismiss an open question', role: 'operator', returns: 'the `Question`', errors: [404, 409] },
  ...([['research', 'research'], ['propose', 'a proposal']] as const).map(([path, what]) => ({
    method: 'post' as const, path: `/ui/api/questions/:id/${path}`, tag: 'Questions' as const, summary: `Shift the job to ${what} from its open question`,
    description: `Issue #548. \`mode\` \`fork\`: a separate job asked for ${what} about the aspect in \`note\` is queued (accepted, with the parent's spec, priority and work tree, \`forkOf\` naming the job and question); the parent keeps waiting on its question, or is parked where the phase-shift settings say \`forkParent: park\` and its executor can park; the fork's accepted result answers the question. \`switch\`: the question is answered with what the job is to do now, and the same job, in its session, moves into the phase (\`phase\`, \`shift\`, \`job.phase_changed\`). No mode: the default of GET /api/phase-shifts. 409: the question is not open, its job no longer waits on it, or its executor cannot write a research report or a proposal (the question's \`shifts\` says so, and lists the modes it offers); or, for a fork, a fork of the same kind from the question still runs (issue #570; the question's \`forks\` shows it).`,
    role: 'operator' as const, body: shiftBody, returns: '`{ question: Question, job: Job, fork?: Job }`', errors: [404, 409],
  })),
  { method: 'get', path: '/api/phase-shifts', tag: 'Questions' as const, summary: 'The phase-shift settings', description: 'Issue #548: `defaultMode` (`fork`, the default, or `switch`), `forkParent` (`wait`, the default, or `park`), `levels` the escalation levels that may shift a job themselves when they suggest it (none, the default: only a person shifts); `choices.levels` the escalation levels there are now.', returns: '`PhaseShiftSettingsView`' },
  { method: 'post', path: '/ui/api/phase-shifts', tag: 'Questions' as const, summary: 'Change the phase-shift settings', description: 'Any part; one left out keeps its value (`phase_shifts.settings_changed`). Applies to the next shift, without a restart. 400: a level that is not an escalation level now.', role: 'admin', body: phaseShiftSettingsBody, returns: '`PhaseShiftSettingsView`', errors: [400] },
  { method: 'post', path: '/ui/api/questions/:id/seen', tag: 'Questions', summary: 'Mark a question seen', role: 'operator', returns: 'the `Question`', errors: [404] },
  ...REVIEW_KINDS.flatMap(reviewOperations),
  { method: 'get', path: '/api/sections', tag: 'State', summary: 'The sections and what is open in each', description: 'Every section type — Questions, Proposals, Research, Logins, Failures, Parked — in nav order (issue #543): `open`, what is open in it (a parked job\'s question is in Parked, not Questions: issue #565); `waiting`, of those, what waits on a person; `high`, of those, how many are a high-priority job\'s; `events`, the event types it emits (subscribe a webhook to them).', returns: '`{ sections: SectionSummary[] }`' },
  { method: 'get', path: '/api/logins', tag: 'Logins', summary: 'List logins', description: 'The logins jobs and escalation runs wait on (a CLI showing a device code), newest first, with the server\'s time (`now`) for their countdowns and the logins settings. `status` `open`: pending or expired. A login\'s `verificationUrl` and `userCode` are answered only to a UI session of the user (the `' + SESSION_HEADER + '` header) whose role is operator or admin, while it is open and while the daemon holds them (`codeKept`; a restart drops them): never to an API token, never to a loopback read without a session.', query: loginsQuery, returns: '`{ now, settings: LoginSettings, logins: LoginView[] }`' },
  { method: 'get', path: '/api/logins/:id', tag: 'Logins', summary: 'One login', description: 'As in `GET /api/logins`, its URL and code to an operator or admin UI session of the user only.', returns: '`LoginView`', errors: [404] },
  { method: 'post', path: '/ui/api/logins/:id/cancel', tag: 'Logins', summary: 'Cancel a login', description: 'The login ends `cancelled` (`auth.cancelled`) and its code is dropped. A herdr job waiting on it is told to stop waiting and go on without it, or to fail. 409: it ended, or what waited on it is no longer running.', role: 'operator', returns: 'the `Login`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/logins/:id/new-code', tag: 'Logins', summary: 'Ask for a new code', description: 'A herdr job waiting on the login is told to start it again and report the new code; the same login takes it (`auth.pending` again, `renewed: true`). Also on an expired login, while its job waits (logins setting `onExpiry: hold`). 409: it ended, what waited on it is no longer running, or its run cannot ask its tool again (a print-mode run).', role: 'operator', returns: 'the `Login`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/logins/settings', tag: 'Logins', summary: 'Change the logins settings', description: 'Either setting, or both; one left out keeps its value. `onExpiry` `fail` (the default): the job fails, its reason the expiry. `hold`: the job keeps waiting for a new code until its own timeout. Applies to the next expiry, without a restart. `warnSec` (10 to 3600, default 60): how long before a code runs out the Logins view warns, or a fifth of the code\'s life when that is longer.', role: 'admin', body: loginSettingsBody, returns: '`LoginSettings`' },
  { method: 'get', path: '/api/failures', tag: 'Failures', summary: 'The failures', description: 'What the failure assessor made of the failed jobs (issue #509): `counts` — the failed jobs not assessed yet (`unassessed`) and the open hand-offs (`needsPerson`), both zero once every failure is processed (issue #517); `handoffs` — Needs a person (issue #516): every failed job automatic handling ended for, open until a person resolves it (issue #551: `actions` says whether each resolution — `continue`, `fixed`, `doneByHand`, `wontDo` — is taken now and why not, `continueResumes` whether Continue resumes its own agent session, `resolution` what a person did, `nextJobId` the job that follows), its item runs again, or nothing waits on it any more — a newer job of its item, its item closed, its job gone (issue #529) — (never dropped by age), oldest first, then those closed in the last day, each with its reason, its assessment summary and its `actions`; `problems` — the open ones, then those resolved in the last day, each with its jobs (`jobIds`), the jobs that wait on its release (`held`) and its `actions`; `recent` — the newest assessed failures nothing settled (a newer job of its item, or its item closed: out of the list, still in `profile`, issue #529), each with its decision, reasons, summary, evidence and `actions`; `profile` — per signature counts and a daily trend over 14 days, and breakdowns by machine, repo and executor; `causes` — the known causes, the named ones first; and the failures `settings`. An action\'s `{ ok: false, why }` is the reason its route refuses it now.', returns: '`FailuresView`' },
  { method: 'post', path: '/ui/api/failures/problems/:id/resolve', tag: 'Failures', summary: 'Resolve a problem', description: 'The problem ends `resolved` (`failure.resolved`, `by: "user"`): new jobs are no longer held for it, and its held jobs run again through the normal queue. 409: it is already resolved.', role: 'operator', returns: 'the `Problem`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/failures/problems/:id/release', tag: 'Failures', summary: 'Release a problem\'s held jobs', description: 'Its held jobs run again now, through the normal queue (`job.rerun`, `by: "assessor"`); while the problem is open, a job it covers is held there again or placed on another machine. 409: no job is held.', role: 'operator', returns: 'the `Problem`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/failures/:id/retry', tag: 'Failures', summary: 'Run a failure\'s job again', description: 'A failure surfaced to a person (or one whose run again was refused): its job\'s item runs again, as Run again does. 409: it already ran again, runs again by itself, waits on its problem, or a newer job of its item exists.', role: 'operator', returns: 'the new `Job`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/failures/handoffs/:id/resolve', tag: 'Failures', summary: 'Resolve a hand-off', description: 'A person says what they did about a failed job in Needs a person (issue #551), and the hand-off closes with it (`handoff.closed` with `resolution`). `action` `continue`: the job goes on with the note — when its own agent session can resume (`continueResumes` on the hand-off), the same job is queued again pinned to its machine and resumes that session in its work tree, told the failure and the note (`job.continued`, `end: "continued"`); else a new job of its item runs, told the earlier error, the assessment and the note (`end: "run_again"`). `fixed`: the person fixed the cause outside the job; a new job of its item runs, told the note (`end: "run_again"`). `done_by_hand`: the person did the work; its job ends finished, `link` (http or https) the work (`end: "done_by_hand"`). `wont_do`: not to be done, or no real failure; `note` says why and is required; its locked entry is dismissed (`end: "wont_do"`). The resolution is kept on the hand-off — who (the signed-in person), when, the note, the link — and told to the job\'s item at its source (`writeBack`): on GitHub one comment naming no person, and the end label (`hopper:done` for done by hand, `hopper:rejected` for won\'t do), never left `hopper:failed`. 409: the action is not taken now (the hand-off\'s `actions` say why: it is closed, it runs again by itself, or a newer job of its item exists).', role: 'operator', body: handoffResolveBody, returns: '`{ handoff, job? }`: the `HandoffView`, and the job that follows — the same job continued, or the new one', errors: [400, 401, 404, 409] },
  { method: 'post', path: '/ui/api/failures/settings', tag: 'Failures', summary: 'Change the failures settings', description: 'Any of them; one left out keeps its value. `maxAttempts` (0 to 10, default 3): retries per job. `backoffSec` (default 60), `backoffFactor` (default 2), `backoffMaxSec` (default 1800): the wait before each retry. `groupThreshold` (default 3) items failed with one signature within `groupWindowMin` minutes (default 60) flag it as a general cause. `auto.retry`, `auto.hold`, `auto.redirect` (default on): whether each decision acts by itself; off, it waits for a person, and with `auto.hold` off no job is held for a problem. `retentionDays` (default 90): how long failure records and resolved problems are kept. `handoffRetentionDays` (default 30): how long a closed hand-off is kept; an open one is never dropped. `handoffNotify` (default on): whether a job handed off to a person tells the webhooks (`handoff.opened` `notify`). Applies without a restart.', role: 'admin', body: failureSettingsBody, returns: '`FailureSettings`' },
  { method: 'post', path: '/ui/api/failures/causes', tag: 'Failures', summary: 'Name a cause', description: 'Names the cause of a signature, with a description and its default decision (`retry`, `hold`, `redirect` or `person`): the next failure with that signature follows it, before any built-in cause. Naming it again replaces it.', role: 'admin', body: failureCauseBody, returns: 'the `KnownCause`' },
  { method: 'post', path: '/ui/api/failures/causes/forget', tag: 'Failures', summary: 'Forget a named cause', description: 'The signature\'s failures follow the built-in causes again. 404: no cause is named for it.', role: 'admin', body: failureForgetBody, returns: '`{ forgotten }`', errors: [404] },
  { method: 'get', path: '/api/minor-decisions', tag: 'Minor decisions', summary: 'Minor decisions: Jev\'s picks and agreement rates', description: 'Minor decisions through Jev first (issue #550): `jev` — whether Jev can be asked now (`available`, `why` not: no `TYPESAFE_API_KEY`); `points` — each decision point (`question-answer`, `failure-assessment`) with its `mode` (`off`, `shadow`: recorded only, `active`: a pick at or above `threshold` that nothing makes consequential is applied), its label and description, and over the last `windowDays` days how often Jev was `asked`, `picked`, how often its pick was `applied`, `compared` with what was decided after, `agreed`, the `agreement` rate (null with nothing compared) and how many were `overridden`; `recent` — the newest picks, each with its options, pick, confidence, whether it was applied and why not, and what was decided.', returns: '`MinorDecisionsView`' },
  { method: 'post', path: '/ui/api/minor-decisions/points/:point', tag: 'Minor decisions', summary: 'Change a decision point\'s settings', description: '`mode` (`off`, `shadow`, `active`; default `shadow`) and `threshold` (0 to 1, default 0.85: the confidence a pick needs to be applied, active); one left out keeps its value. Applies from the next decision (`minor_decision.settings_changed`). 404: no such decision point.', role: 'admin', body: decisionPointBody, returns: 'the point\'s `DecisionPointSettings`', errors: [404] },
  { method: 'post', path: '/ui/api/minor-decisions/picks/:id/override', tag: 'Minor decisions', summary: 'Override a pick', description: 'What the decision should have been: `actual`, one of the pick\'s option ids (`minor_decision.overridden`). Counts in the agreement rate in place of what was compared. It changes nothing already done. 404: no such pick in the window; 400: not one of its options.', role: 'operator', body: overrideBody, returns: 'the `MinorDecisionPickView`', errors: [404] },
  { method: 'post', path: '/ui/api/rules', tag: 'Questions', summary: 'Replace the rules', description: '`version` is the one read from GET /api/question-gates.', role: 'admin', body: rulesBody, returns: 'the new rules view', errors: [409] },
  { method: 'get', path: '/api/machines', tag: 'Machines and usage', summary: 'Machines, their lanes and usage', returns: '`{ machines: (MachineSnapshot & { lanes, usage })[] }`' },
  { method: 'get', path: '/api/machines/history', tag: 'Machines and usage', summary: 'The resource graph: every machine\'s resources per graph step', description: 'The user\'s own machine samples over the graph range: per machine and graph step the peak share used of CPU (busy), memory, swap and disk (its home\'s filesystem), and of its lanes in use, and the gaps where the machine gave no sample (offline). `range` (a preset) or `from` and `to`; default the last day. The graph step follows the range: 15 minutes up to a day, an hour up to 4, 6 hours up to 14, a day up to 60, else a week. `tz` (minutes east of UTC) puts day and week steps at the viewer\'s midnight.', query: usageHistoryQuery, returns: '`MachineHistory`', errors: [400] },
  { method: 'get', path: '/api/machines/:id/history', tag: 'Machines and usage', summary: 'The resource graph of one machine', description: 'As GET /api/machines/history, the one machine only: per machine and graph step the peak share used of CPU (busy), memory, swap and disk (its home\'s filesystem), and of its lanes in use, and the gaps where the machine gave no sample (offline). `range` (a preset) or `from` and `to`; default the last day. The graph step follows the range: 15 minutes up to a day, an hour up to 4, 6 hours up to 14, a day up to 60, else a week. `tz` (minutes east of UTC) puts day and week steps at the viewer\'s midnight.', query: usageHistoryQuery, returns: '`MachineHistory`', errors: [400] },
  { method: 'get', path: '/api/machines/config', tag: 'Machines and usage', summary: 'What the Machines view edits', returns: 'every machine (name, connection, options), the executors, the machine defaults, the detected ssh targets and which of them are this machine, the hopper\'s own public ssh key, why this machine cannot be added (in a container), the plugins config version' },
  { method: 'post', path: '/ui/api/machines', tag: 'Machines and usage', summary: 'Add this machine, or attach one over ssh (edit or remove it through /ui/api/plugins)', description: 'Without `ssh`: this machine, under `name`, its jobs in the herdr session `session` (default `hopper`), which the daemon starts. With `ssh`: a detected ssh target or a plain `[user@]host`; one that is this machine is added as this machine, with no ssh. `hostKey`: the host key confirmed from /ui/api/machines/host-key, else the one ~/.ssh/known_hosts holds. In a container this machine is refused.', role: 'admin', body: machinesEditBody, returns: 'the new machines config', errors: [409] },
  { method: 'post', path: '/ui/api/machines/host-key', tag: 'Machines and usage', summary: 'The host key a new ssh target would be pinned to, to confirm before attaching it', description: 'The one ~/.ssh/known_hosts holds (`known`), else the one the target presents now, with its SHA256 fingerprint. Writes nothing.', role: 'admin', body: machineHostKeyBody, returns: '`{ ssh, hostKey, fingerprint, known }`', errors: [409] },
  { method: 'post', path: '/ui/api/machines/join', tag: 'Machines and usage', summary: 'A one-time join code for Add machine', description: 'For the session\'s user, for 10 minutes, once. A machine joins with `<hopper URL>#<code>`: the line Add machine shows runs the hopper client\'s join (POST /client/join) with it. Only the code\'s hash is kept. `template`: the template a sandbox box joins as (issue #558); 404 when there is none of that name.', role: 'admin', body: machineJoinBody, returns: '`{ code, expiresAt }`', errors: [404] },
  { method: 'post', path: '/ui/api/machines/defaults', tag: 'Machines and usage', summary: 'Set what a machine attached here starts with: its lanes and executors', role: 'admin', body: machineDefaultsBody, returns: 'the new machines config', errors: [409] },
  { method: 'get', path: '/api/usage', tag: 'Machines and usage', summary: 'Usage readings', returns: '`UsageReport`' },
  { method: 'get', path: '/api/usage/history', tag: 'Machines and usage', summary: 'The usage graph: usage history per graph step', description: 'The user\'s own usage samples over the graph range, per graph step: per account and usage window — one line however many machines read the account — the highest share of the limit used in each step, the gaps (no sample for far longer than the account is read) and the resets of the usage window. `range` (a preset) or `from` and `to` override the user\'s saved choice (default: the last 7 days) without saving it. The graph step follows the range: an hour up to 2 days, 6 hours up to 4, a day up to 60, else a week. `tz` (minutes east of UTC) puts day and week steps at the viewer\'s midnight.', query: usageHistoryQuery, returns: '`UsageHistory`', errors: [400] },
  { method: 'post', path: '/ui/api/usage-history/view', tag: 'Machines and usage', summary: 'Save the usage graph\'s range', description: 'The session\'s user\'s own choice; the next GET /api/usage/history without a range reads it.', role: 'viewer', body: usageGraphViewBody, returns: '`{ view: UsageGraphView }`' },
  { method: 'post', path: '/ui/api/usage-history/retention', tag: 'Machines and usage', summary: 'Set the history retention', description: 'How many days usage samples are kept (default 90). Applied at once: older samples are deleted.', role: 'admin', body: historyRetentionBody, returns: '`{ retentionDays, pruned }`' },
  { method: 'get', path: '/api/priority-lanes', tag: 'Machines and usage', summary: 'Priority lanes', description: 'The lanes high-priority jobs get first (issue #535) and why: `settings` (the high-priority threshold, the count of priority lanes, `whenIdle` — `keep-free` or `share` —, the window and minimum runs of lane reliability, `manual` the lanes an admin chose) with their `defaults`; `chosen` the priority lanes, best first, and `by` how (`reliability`, `manual`, `none`); `lanes` every lane of every machine with its figures over the window — runs, finished, failed, lane faults (failures that were not the job\'s fault), lane faults in the last day, success rate, median time to start, the score it is ranked by — its `rank`, whether it is a priority lane, and the `reason`.', returns: '`PriorityLanesView`' },
  { method: 'post', path: '/ui/api/priority-lanes/settings', tag: 'Machines and usage', summary: 'Set the priority lane settings', description: 'Any of `highPriority` (1..100), `count` (0..32), `whenIdle` (`keep-free`, `share`), `windowDays` (1..90), `minRuns` (1..1000) and `manual` (lanes of the machines, best first; `null`: choose by reliability again); one left out keeps its value. Stored for the user and read at each Decision: they apply without a restart.', role: 'admin', body: priorityLaneSettingsBody, returns: '`PriorityLanesView`' },
  { method: 'get', path: '/api/blast-radius', tag: 'Machines and usage', summary: 'Blast radius: each machine\'s discovery, rating and gate', description: 'Issue #542. Per machine: whether it can be discovered (a container target cannot), its last `discovery` — when, what it found (the PATH and its executables, the known tools\' versions, each AWS identity and what IAM policy simulation allows it of `awsActions.write`, each kubectl context and what `auth can-i` says of `kubeChecks`, the credential variables and files present — names only, never a secret), what changed since the one before, `grew` when it raised the level —, its `rating` with the rules now (`level` low, medium or high; each `reach` with its access — read, write, admin, unconfirmed —, whether it is prod, and its evidence), its actor machine declaration with `mismatch`, and `gated`: why the gate keeps it from ordinary placement. With the `settings` and their `defaults`.', returns: '`BlastRadiusView`' },
  { method: 'post', path: '/ui/api/blast-radius/settings', tag: 'Machines and usage', summary: 'Set the blast-radius settings', description: 'Any of `gateAt` (`high`, `medium`, `off`: machines rated at or above it are gated; actor machines always are), `pass` (`labels`, `repos` as owner/name, `minPriority` 0..100 or `null`: a job with one of them passes the gate), `rules` (`prodPatterns`, `prodAccounts` as 12-digit AWS account ids, `unconfirmed`: `write` or `read`), `actors` (each `machineId` a machine, its `purpose`, the `expected` level) and `everyMinutes` (5..1440); each replaced whole, one left out keeps its value. Stored for the user and read at each Decision: they apply without a restart.', role: 'admin', body: blastRadiusSettingsBody, returns: '`BlastRadiusView`', errors: [400] },
  { method: 'post', path: '/ui/api/blast-radius/discover', tag: 'Machines and usage', summary: 'Discover a machine now', description: 'Runs the discovery on `machineId`, or on every online machine, through its own connection, and answers when it is done. Discovery only reads: identities, configuration, IAM policy simulation, `kubectl auth can-i`.', role: 'operator', body: discoverBody, returns: '`BlastRadiusView`', errors: [404] },
  { method: 'post', path: '/ui/api/jobs/:id/gate-pass', tag: 'Jobs', summary: 'Let a job held at the blast-radius gate through', description: 'The job may then run on a gated machine (`gatePass`, `job.gate_passed`). 409: the job is not held at the gate.', role: 'admin', returns: 'the `Job`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/usage/limits', tag: 'Machines and usage', summary: 'Set the usage limits', description: 'The soft limit, past which a machine\'s lane cap scales down, and the hard limit, at which it starts nothing: fractions from 0 to 1, soft below hard. Stored for the user: they win over `HOPPER_SOFT_LIMIT` / `HOPPER_HARD_LIMIT` from now on, and the next Decision uses them.', role: 'admin', body: usageLimitsBody, returns: '`{ limits: UsageLimits }`' },
  { method: 'get', path: '/api/plugins', tag: 'Plugins and routing', summary: 'Every role, instance and plugin', returns: '`PluginsReport`' },
  { method: 'get', path: '/api/plugin-store', tag: 'Plugins and routing', summary: 'The plugin store: its catalogue and the store installs', returns: '`PluginStoreReport`' },
  { method: 'post', path: '/ui/api/plugin-store', tag: 'Plugins and routing', summary: 'Set the plugin store; install, update or remove a plugin from it', description: 'Only the instance admin (issue #240). Read the plugin store again, set the plugin store (the default plugin store, none, or a git repository; issue #445) and read it, install a plugin its catalogue lists into the plugin dir (again: an update to the store\'s head), or remove a store install that the plugins config does not name.', role: 'admin', body: pluginStoreBody, returns: 'the new `PluginStoreReport`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/plugins', tag: 'Plugins and routing', summary: 'Edit plugin instances', description: 'Set an instance\'s options (every one, command-bearing ones too; a machine also takes a new name, `rename`), select the plugin of a one-instance role, add or remove an instance, or rescan.', role: 'admin', body: pluginsEditBody, returns: 'the new `PluginsReport`', errors: [404, 409] },
  { method: 'post', path: '/ui/api/notifiers', tag: 'Plugins and routing', summary: 'Run a notifier\'s action', description: 'A running notifier instance, by name, does one of the actions GET /api/plugins lists for it: `test` sends one marked test payload, one attempt; `send-open` sends every question open at the human now. Answers what it did, with the receiver\'s HTTP status. Nothing is stored.', role: 'admin', body: notifierActionBody, returns: '`NotifierActionResult`', errors: [400, 404] },
  { method: 'get', path: '/api/routing', tag: 'Plugins and routing', summary: 'Routing rules', returns: 'the rules as configured and their report' },
  { method: 'post', path: '/ui/api/routing', tag: 'Plugins and routing', summary: 'Replace the routing rules', description: 'Applies to new jobs, and to waiting jobs that have not started on the next sync of their source.', role: 'admin', body: routingEditBody, returns: 'the new routing report', errors: [409] },
  { method: 'get', path: '/api/vault', tag: 'Vault', summary: 'Vault secrets (metadata only) and templates', description: 'Each secret\'s name, scope, who set it and when, who last changed it and when. Each template with its image, its scope, its last approval, what waits for approval (`pending`) and what its boxes may be given now (`gives`). Never a value, to any role. `problem` when the runtime gives no `HOPPER_TOKEN_KEY`. Not cached.', returns: '`{ secrets, templates, problem? }`' },
  { method: 'post', path: '/ui/api/vault', tag: 'Vault', summary: 'Set or remove a vault secret; save, remove or approve a template', description: '`set` stores a new secret, or a new value (and scope, when given) for one: kept encrypted in the database and never answered back. `remove` deletes it. `save-template` saves a template: its image and the vault secrets its boxes may ask for; a scope wider than the one approved, or a new image, waits for `approve-template`, which approves it as it is. `remove-template` removes one. Not cached. 503 when the runtime gives no `HOPPER_TOKEN_KEY` to encrypt it with.', role: 'admin', body: vaultEditBody, returns: 'the new view, as GET /api/vault', errors: [404, 503] },
  { method: 'get', path: '/api/webhooks', tag: 'Webhooks', summary: 'Webhook subscriptions', description: 'Each with when its signing secret last changed (`secretChangedAt`) — or, for a subscription from before with none stored, the runtime variable it reads (`secretEnv`) — and why it cannot sign, if so (`secretProblem`). Never a secret.', returns: '`{ subscriptions }`' },
  { method: 'get', path: '/api/webhooks/deliveries', tag: 'Webhooks', summary: 'Webhook deliveries', query: deliveriesQuery, returns: '`{ deliveries }`, newest first' },
  { method: 'post', path: '/ui/api/webhooks', tag: 'Webhooks', summary: 'Add, edit or remove a subscription; replace or rotate its signing secret', description: 'The signing secret is the hopper\'s own, kept encrypted in the database and never answered back. `add` takes one typed in (`secret`: 32 to 4096 printable ASCII characters, no spaces), or none, and then the hopper makes one; `replace` stores one typed in; `rotate` has the hopper make one. A secret the hopper made is in this answer only (`generatedSecret`): copy it to the receiver. Applies from the next delivery. Not cached. 503 when the runtime gives no `HOPPER_TOKEN_KEY` to encrypt it with.', role: 'admin', body: webhooksEditBody, returns: 'the new view, as GET /api/webhooks, with `generatedSecret` when the hopper made one', errors: [404, 409, 503] },
  { method: 'post', path: '/ui/api/webhooks/test', tag: 'Webhooks', summary: 'Send a test event to a subscription', description: 'One signed `webhook.test` event, one attempt, whatever events the subscription names. Answers the receiver\'s HTTP result, or why nothing was sent. No delivery is stored; nothing is appended to the event log.', role: 'admin', body: webhookTestBody, returns: '`{ ok, status?, detail }`', errors: [404] },
  { method: 'get', path: '/api/events', tag: 'Events', summary: 'The event log', description: 'Without `after`: the newest `limit` events, oldest first.', query: eventsQuery, returns: '`{ events: DomainEvent[] }` (envelope schema below; `data` per type in docs/schemas)' },
  { method: 'get', path: '/api/events/stream', tag: 'Events', summary: 'Live events (server-sent events)', description: 'Replays after `after` (or `Last-Event-ID`), then live. Also `delivery.updated`, `source.updated` `usage.recorded` (new usage samples kept: `{ added }`) and `machine.recorded` (new machine samples kept: `{ added }`) without an id, and a ping comment every 15 s. Beyond loopback the session goes in the `session` query parameter: EventSource sends no headers.', query: streamQuery, answers: 'sse', returns: 'an event stream' },
  { method: 'get', path: '/api/update', tag: 'Self-update', summary: 'Installed version and available update', returns: '`UpdateStatus`' },
  { method: 'get', path: '/api/update/history', tag: 'Self-update', summary: 'Version history', description: 'The versions the installed commit is made of, newest first: each commit of the tracked branch (first parent) that added What\'s new lines, with its date and those lines. Checks the update repository first when it lacks the installed commit. Always carries `build`: what the running build\'s install.json says (an install or an image), whole or not; `reason` names what it lacks.', returns: '`VersionHistory`' },
  { method: 'post', path: '/ui/api/update', tag: 'Self-update', summary: 'Check, apply, or change update settings', description: 'Only the instance admin: the first person to sign in with GitHub, else the oldest user (issue #240).', role: 'admin', body: updateBody, returns: '`UpdateStatus`', errors: [409] },
  { method: 'get', path: '/api/users', tag: 'Users', summary: 'The users of this hopper', description: 'Only the instance admin (issue #240). Id, name and when each was added: nothing of a user\'s own data. Loopback, or a UI session with role **admin**.', returns: '`{ users: UserView[] }`, oldest first', errors: [403] },
  { method: 'get', path: '/api/instance', tag: 'Users', summary: 'The totals across every user', description: 'Only the instance admin (issue #240). Users, jobs not ended by status, open questions, lanes (open and busy), jobs ended in the last 24 hours by how they ended, usage readings summed per unit and usage window: summed over every user, never one user\'s share, nothing named. What an admin reads of the users\' work. Loopback, or a UI session with role **admin**.', returns: '`InstanceTotals`', errors: [403] },
  { method: 'get', path: '/api/instance/usage-history', tag: 'Users', summary: 'The usage graph summed over every user', description: 'Only the instance admin. Every user\'s usage graph lines summed per unit, usage window and graph step (summed used over summed limit), with how many lines each point sums: never one user\'s share, nothing named. The same query as GET /api/usage/history; no saved choice.', query: usageHistoryQuery, returns: '`InstanceUsageHistory`', errors: [400, 403] },
  { method: 'post', path: '/ui/api/users', tag: 'Users', summary: 'Add a user', description: 'Only the instance admin (issue #240). A user of its own: its jobs, questions, events, plugins, webhooks and credentials apart from every other user\'s. Answers a one-time login link for it per UI origin, to hand over (none when local sign-in is off).', role: 'admin', body: usersEditBody, returns: '`UserAdded`: `{ user, links }`', errors: [409] },
  { method: 'get', path: '/ui/api/session', tag: 'Sign-in', summary: 'This session (logged out: whose work a read shows), the sign-in on offer, and whether several users make sign-in required', returns: '`SessionView`' },
  { method: 'post', path: '/ui/login', tag: 'Sign-in', summary: 'Sign in with a one-time login code', description: 'A code from a device link or a new user\'s login link. Answers a page that stores the session token for the UI.', body: loginBody, form: true, answers: 'html', returns: 'a page holding the session token' },
  { method: 'post', path: '/ui/auth/none', tag: 'Sign-in', summary: 'Start a session with no sign-in (the sign-in config `none`)', returns: '`{ token, expiresAt, user }`' },
  { method: 'post', path: '/ui/auth/gateway', tag: 'Sign-in', summary: 'Start a session from the token an auth gateway forwards', description: 'For a hopper behind an auth gateway (a gateway realm): the gateway signs people in and adds their token to the request; the gateway realms that are on check it, in order (a JWT against the issuer\'s keys, or token introspection), and the first that accepts it signs in. 403 for no token or one refused; 502 when none accepted it and an issuer could not be reached.', returns: '`{ token, expiresAt, user }`', errors: [502] },
  { method: 'post', path: '/ui/auth/password', tag: 'Sign-in', summary: 'Sign in with a username and password', description: 'Tried against the LDAP realms that are on, in order: the first that accepts the password signs in. The hopper keeps no password accounts of its own. 502 when none accepted it and a realm could not be reached.', body: passwordBody, returns: '`{ token, expiresAt, user }`', errors: [502] },
  { method: 'get', path: '/ui/auth/:name/start', tag: 'Sign-in', summary: 'Begin sign-in with an OIDC, GitHub or SAML realm', query: startQuery, answers: 'redirect', returns: 'a redirect to the realm\'s identity provider' },
  { method: 'get', path: '/ui/auth/:name/callback', tag: 'Sign-in', summary: 'OIDC and GitHub return here', answers: 'html', returns: 'a page that completes the sign-in' },
  { method: 'post', path: '/ui/auth/:name/callback', tag: 'Sign-in', summary: 'SAML posts its response here', answers: 'html', returns: 'a page that completes the sign-in' },
  { method: 'post', path: '/ui/auth/:name/device', tag: 'Sign-in', summary: 'Start signing in with GitHub', description: 'A github realm (issue #214): the device code to enter at the provider and where, through the hopper\'s app (its public client id, no secret). `binding`: a random value this browser keeps; only it can take the session.', body: deviceStartBody, returns: '`{ flow, userCode, verificationUri, expiresAt }`', errors: [400, 404, 502] },
  { method: 'post', path: '/ui/auth/device/poll', tag: 'Sign-in', summary: 'Follow a GitHub sign-in', description: '`waiting` until the code is approved; then the session, once — and the token the provider granted becomes the user\'s connected account, what their jobs work through. 403 when no role rule grants the account a role, or for another browser.', body: devicePollBody, returns: '`{ state: waiting }` or `{ state: signed-in, token, expiresAt, user }`' },
  { method: 'post', path: '/ui/auth/complete', tag: 'Sign-in', summary: 'Trade a sign-in ticket for a session', body: completeBody, returns: '`{ token, expiresAt, user }`' },
  { method: 'get', path: '/ui/auth/:name/metadata', tag: 'Sign-in', summary: 'SAML service provider metadata', answers: 'xml', returns: 'SAML metadata', errors: [404] },
  { method: 'post', path: '/ui/api/device-link', tag: 'Sign-in', summary: 'A login link for another device, per LAN name', description: '`keep` names the code shown: while it is live the same links come back; once it is used or expired, a fresh code.', role: 'admin', body: deviceLinkBody, returns: '`{ links: string[] }`', errors: [409] },
  { method: 'post', path: '/ui/api/logout', tag: 'Sign-in', summary: 'End this session', role: 'viewer', returns: '`{ ok: true }`' },
  { method: 'get', path: '/api/realms', tag: 'Sign-in', summary: 'The realms, in order, with their settings', description: 'Only the instance admin (issue #240). Each realm\'s settings (never a secret: `secrets` names the ones set), whether it is on, whether the environment set it up, and for OIDC and SAML the URLs to register with the identity provider; the first GitHub admin and the user they sign in as; everyone who has signed in, with their role and whether they are a super admin (`people`); local sign-in, no sign-in, and the version of it all. Loopback, or a UI session with role **admin**.', returns: '`RealmsView`', errors: [403] },
  { method: 'get', path: '/api/access', tag: 'Access', summary: 'Access: OpenFGA, the model, the approvals, the decisions', description: 'Only the instance admin (issue #559). `status` — whether OpenFGA can be asked (`not-configured`, `connected`: everything pushed, `unreachable`: every mint is denied) and `why` not; `model` — the access model (OpenFGA DSL) and its `version`; `templates` — each template\'s approvals, each an operation profile (an operation on an asset) with who approved it, when, and the relationship `chain` from the template to the asset; `revoked` — the newest revoked approvals; `decisions` — the newest mint decisions, each allowed or denied with its reason and, allowed, the relationship `path` from the job.', returns: '`AccessView`', errors: [403] },
  { method: 'post', path: '/ui/api/access', tag: 'Access', summary: 'Approve, revoke, try a check, or save the access model', description: 'Only the instance admin (issue #559). `approve` — a template for an operation on an asset (what the vault\'s gate writes, issue #558); `revoke` — an approval by its `id`: the next check is denied; `check` — whether a live job of the template would get the operation on the asset now (a trial, recorded with the answer); `model` — the access model in OpenFGA DSL, against the `version` read: it must keep every relation the hopper writes or asks, and OpenFGA must take it when it can be asked (400 naming why; 409 when the model moved). A change is pushed to OpenFGA before the answer; one it could not take yet is pushed before the next check, which is denied until then. 404: no such approval.', role: 'admin', body: accessEditBody, returns: 'the new view, as GET /api/access; `check`: the `AccessDecisionRecord`', errors: [403, 404, 409] },
  { method: 'post', path: '/ui/api/realms', tag: 'Sign-in', summary: 'Change sign-in: the realms, the login code and no sign-in', description: 'Only the instance admin (issue #240). Add or replace a realm from its fields (a secret — `clientSecret`, `bindPassword` — is stored; left out it keeps the stored one, `null` removes it), remove, move, or turn one on or off; set local sign-in and no sign-in; make someone who has signed in admin (`admin`), or — a super admin only, else 403 — super admin, or hand your own over (`super-admin`, `transfer`) — against the `version` read. A regular admin\'s change that would change who is super admin is refused (403); naming someone who never signed in, 404. Applies at once: sign-in and the stored sessions follow it. Refused (400) when the result would not load, naming the field; (409) when the sign-in config moved, when the change would end the acting session\'s admin role, or when it would turn no sign-in on while the hopper has more than one user.', role: 'admin', body: realmsEditBody, returns: 'the new view, as GET /api/realms', errors: [403, 404, 409] },
];

const TAGS: Record<Tag, string> = {
  State: 'What the hopper is doing: health, the queue, decisions, the router.',
  Jobs: 'Jobs and the job sources they are pulled from.',
  Questions: 'Questions a running job asks, and the gates they pass.',
  Proposals: 'Proposals a job wrote instead of doing the work: reviewed by the reviewer levels, signed off by a person. A review section, as Research is. Never a question.',
  Research: 'Research reports a job wrote instead of doing the work: accepted, dug deeper on or steered by a person, each round kept. A review section, as Proposals is. Never a question.',
  Logins: 'Logins a job or run waits on (a CLI showing a device code): never a question.',
  Failures: 'What the failure assessor made of the failed jobs: problems grouped from shared causes, assessed failures, the failure profile, and its settings.',
  'Minor decisions': 'Bounded choices Jev makes first, before a model or a person: each decision point\'s mode, threshold and agreement rate, and every pick.',
  'Machines and usage': 'Where jobs run, and the usage that throttles lanes.',
  'Plugins and routing': 'Which plugin instance fills which role, and the routing rules.',
  Webhooks: 'Subscribers to the event log, kept in the database.',
  Vault: 'Write-only secrets for jobs: set once, never read back.',
  Events: 'The event log, read back or streamed.',
  'Self-update': 'The install and the update repository.',
  Users: 'The people one hopper works for, each with their own work, kept apart.',
  'Sign-in': 'UI sessions: sign-in, the session, logout.',
  Access: 'OpenFGA decides each credential a job is given: the approvals, the access model, and every decision.',
};

const DESCRIPTION = `The hopper daemon's HTTP API.

**Users.** Every user's work is their own. A read or a change acts for the session's user. A loopback read without a session reads the one user's work while the hopper has one user; with more, it reads no user's work (401). An admin runs the instance — the users, the plugin store, self-update and sign-in — and reads the users' work only as totals (\`GET /api/instance\`).

**Reading.** Every \`GET /api/*\` route reads. From loopback (\`127.0.0.1\` or \`localhost\` with the port) it needs nothing. From a LAN name or the public URL it needs a UI session: the token in the \`${SESSION_HEADER}\` header.

**Changing.** The only changes are \`POST /ui/api/*\`. Each needs a UI session (\`${SESSION_HEADER}\`) whose role allows it, the exact Origin of a UI page, and a JSON body; else 403. No route creates a job: jobs come from job sources.

**A session.** Sign in from the UI. The UI keeps the token in this origin's localStorage under \`jh_session\`; paste it under Authentication here to try the routes that need it.

**Host.** Every request must name this daemon in Host; another Host is 421.

**Errors.** \`{ "error": string }\` with the status: 400 a malformed request, 401 no session for a LAN or public read, 403 a refused change, 404 nothing by that id, 409 not possible in the current state, 421 a misdirected Host.`;

const ERROR_TEXT: Record<number, string> = { 400: 'malformed request', 401: 'no session for a LAN or public read, or for a user\'s work on a hopper with several users', 403: 'refused: no session, role too low, wrong Origin, or not JSON', 404: 'not found', 409: 'not possible in the current state' };

/** JSON Schema for a request part, as the route parses its input. */
const schemaOf = (s: z.ZodType): Record<string, unknown> => {
  const { $schema: _, ...rest } = z.toJSONSchema(s, { io: 'input', unrepresentable: 'any' }) as Record<string, unknown>;
  return rest;
};

const openApiPath = (path: string): string => path.replace(/:([A-Za-z]+)/g, '{$1}');

function parameters(op: Operation): unknown[] {
  const out: unknown[] = [];
  if (op.path.includes(':id')) out.push(id(op.tag === 'Questions' ? 'question' : op.tag === 'Jobs' ? 'job' : op.tag === 'Logins' ? 'login' : op.tag === 'Proposals' ? 'proposal' : op.tag === 'Research' ? 'research report' : op.tag === 'Failures' ? (op.path.includes('/problems/') ? 'problem' : op.path.includes('/handoffs/') ? 'hand-off' : 'failure record') : 'decision'));
  if (op.path.includes(':name')) out.push(name);
  if (op.query) {
    const s = schemaOf(op.query) as { properties?: Record<string, Record<string, unknown>>; required?: string[] };
    for (const [n, schema] of Object.entries(s.properties ?? {})) {
      out.push({ name: n, in: 'query', required: s.required?.includes(n) ?? false, schema, ...(typeof schema.description === 'string' ? { description: schema.description } : {}) });
    }
  }
  return out;
}

const MEDIA = { html: 'text/html', sse: 'text/event-stream', xml: 'application/samlmetadata+xml' } as const;
const ERROR = { description: '', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } };

function responses(op: Operation): Record<string, unknown> {
  const statuses = [...(op.query || op.body ? [400] : []), ...(op.role ? [403] : []), ...(op.path.startsWith('/api/') ? [401] : []), ...(op.errors ?? [])];
  const ok = op.answers === 'redirect'
    ? { 302: { description: op.returns } }
    : { 200: { description: op.returns, content: { [op.answers ? MEDIA[op.answers] : 'application/json']: op.path === '/api/events' ? { schema: { type: 'object', properties: { events: { type: 'array', items: { $ref: '#/components/schemas/Event' } } } } } : {} } } };
  return { ...ok, ...Object.fromEntries([...new Set(statuses)].sort().map((s) => [s, { ...ERROR, description: ERROR_TEXT[s] ?? '' }])) };
}

function operation(op: Operation): Record<string, unknown> {
  const roleNote = op.role ? `Needs a UI session with role **${op.role}** or above.` : undefined;
  return {
    tags: [op.tag],
    summary: op.summary,
    ...(op.description || roleNote ? { description: [op.description, roleNote].filter(Boolean).join('\n\n') } : {}),
    operationId: `${op.method}${op.path.replace(/[/:-](\w)/g, (_m, c: string) => c.toUpperCase())}`,
    parameters: parameters(op),
    ...(op.body ? { requestBody: { required: true, content: { [op.form ? 'application/x-www-form-urlencoded' : 'application/json']: { schema: schemaOf(op.body) } } } } : {}),
    // A read needs nothing on loopback and a session or a token beyond it (the API door); a mutation always needs a session.
    security: op.role ? [{ uiSession: [] }] : op.path.startsWith('/api/') ? [{}, { uiSession: [] }, { apiToken: [] }] : [],
    responses: responses(op),
  };
}

/** The OpenAPI 3.1 document of this daemon at `version`. */
export function openApiDocument(version: string): Record<string, unknown> {
  const paths: Record<string, Record<string, unknown>> = {};
  for (const op of OPERATIONS) (paths[openApiPath(op.path)] ??= {})[op.method] = operation(op);
  return {
    openapi: '3.1.1',
    info: { title: 'hopper', version, description: DESCRIPTION },
    tags: Object.entries(TAGS).map(([n, d]) => ({ name: n, description: d })),
    paths,
    components: {
      securitySchemes: {
        uiSession: { type: 'apiKey', in: 'header', name: SESSION_HEADER, description: 'A UI session token (localStorage `jh_session` in a signed-in UI).' },
        apiToken: { type: 'http', scheme: 'bearer', description: 'Reads only (the API door): a gateway realm\'s JWT, or a GitHub token of an account that is a user\'s connected GitHub account. It reads as the user that identity signed in as in the UI; it signs nobody in.' },
      },
      schemas: {
        Error: { type: 'object', properties: { error: { type: 'string' } }, required: ['error'] },
        Event: schemaOf(ENVELOPE_SCHEMA),
      },
    },
  };
}

/** Where the reference stands apart from the served routes; empty when they agree. */
export function referenceDrift(doc: { paths: Record<string, Record<string, unknown>> }, routes: { method: string; url: string }[]): string[] {
  const isApi = (url: string) => url.startsWith('/api/') || (url.startsWith('/ui/') && !url.startsWith('/ui/assets/'));
  const served = new Set(routes.filter((r) => r.method !== 'HEAD' && isApi(r.url)).map((r) => `${r.method} ${openApiPath(r.url)}`));
  const documented = new Set(Object.entries(doc.paths).flatMap(([p, ops]) => Object.keys(ops).map((m) => `${m.toUpperCase()} ${p}`)));
  const show = (key: string) => key.replace(/\{(\w+)\}/g, ':$1');
  return [
    ...[...served].filter((k) => !documented.has(k)).map((k) => `${show(k)} is served but not in the API reference (src/http/openapi.ts)`),
    ...[...documented].filter((k) => !served.has(k)).map((k) => `${show(k)} is in the API reference (src/http/openapi.ts) but not served`),
  ];
}
