// Renders docs/events.md from the schemas, so the document cannot drift from them.
import { EVENT_SCHEMA_VERSIONS, EVENT_TYPES, type EventType } from '../domain/types.ts';
import { EVENT_EXAMPLES } from './examples.ts';
import { exportJsonSchemas } from './export.ts';

const WHEN: Record<EventType, string> = {
  'job.queued': 'A job was accepted (pushed, or pulled from a source).',
  'job.prioritized': 'Jev advice arrived for a job; once per job, whatever its status then.',
  'job.held': 'A Decision held a job and its hold reason changed.',
  'job.approved': 'A human approved a job Jev routed to `ask_human`.',
  'job.claimed': 'A Decision assigned a job to a lane.',
  'job.started': 'The executor began running a claimed job.',
  'job.progressed': 'An executor reported progress; at most one per job per 500 ms.',
  'job.finished': 'A job ended successfully.',
  'job.failed': 'A job ended with an error.',
  'job.cancelled': 'A job was cancelled.',
  'job.requeued': 'A job went back to the queue (restart recovery, or a question answered). `reason` is a free string.',
  'job.reprioritized': 'A source re-sorted a waiting job.',
  'lane.opened': 'A Decision opened a lane.',
  'lane.closed': 'A lane closed (decision reason, `drained`, or `daemon restart`).',
  'decision.made': 'The engine recorded a Decision.',
  'jev.mode_changed': 'The Jev mode was switched.',
  'question.asked': 'A running job paused on a question.',
  'question.escalated': 'A question was passed to a tier (opus, fable, human), or a human was re-notified.',
  'question.answered': 'A tier or a human answered a question.',
  'question.expired': 'The human tier timed out and the job fails.',
};

type Prop = Record<string, unknown>;

function typeOf(p: Prop): string {
  if (Array.isArray(p.enum)) return p.enum.map((v) => `\`${String(v)}\``).join(' \\| ');
  if (Array.isArray(p.anyOf)) return (p.anyOf as Prop[]).map(typeOf).join(' \\| ');
  if (p.type === 'array') return `${typeOf((p.items ?? {}) as Prop)}[]`;
  if (typeof p.type === 'string') return p.type;
  return 'any';
}

function fieldRows(schema: Prop): string {
  const props = (schema.properties ?? {}) as Record<string, Prop>;
  const required = new Set((schema.required ?? []) as string[]);
  const rows = Object.entries(props).map(([k, p]) => `| \`${k}\` | ${typeOf(p)} | ${required.has(k) ? 'yes' : 'no'} |`);
  return rows.length ? ['| field | type | required |', '|---|---|---|', ...rows].join('\n') : '`data` is `{}`.';
}

export function renderEventsMarkdown(): string {
  const files = exportJsonSchemas();
  const out = [
    '# Events',
    '',
    '<!-- generated by `npm run schemas` from src/events — do not edit -->',
    '',
    'Every event (stored, SSE, `/api/events`, webhook body) is the envelope below. `schemaVersion` is the',
    "version of **that type's** payload schema; the JSON Schema for each is in `docs/schemas/<type>.v<N>.json`.",
    'An additive (optional) field keeps the version; a removed, renamed or retyped field bumps it and adds',
    '`<type>.v<N+1>.json` — the old file stays as documentation of what older consumers received.',
    '',
    'Events stored before phase 3 read as v1 and are not re-validated.',
    '',
    '```json',
    '{ "schemaVersion": 1, "seq": 1, "id": "uuid", "type": "job.queued", "at": "ISO",',
    '  "jobId": "…", "laneId": "…", "machineId": "…", "decisionId": "…", "questionId": "…", "data": { … } }',
    '```',
    '',
    'Schema: `docs/schemas/envelope.v1.json`. Payloads are strict: unknown keys are rejected.',
  ];
  for (const t of EVENT_TYPES) {
    const v = EVENT_SCHEMA_VERSIONS[t];
    out.push('', `## \`${t}\``, '', `Version ${v} (\`docs/schemas/${t}.v${v}.json\`). ${WHEN[t]}`, '',
      fieldRows(files[`${t}.v${v}.json`] as Prop), '', '```json', JSON.stringify(EVENT_EXAMPLES[t], null, 2), '```');
  }
  return `${out.join('\n')}\n`;
}
