// One example `data` payload per event type, shaped like the real emitters produce them.
// Used by docs/events.md and by the schema tests.
import type { EventType } from '../domain/types.ts';

const advice = { action: 'proceed_full', reason: 'ok', details: { intent: 'x', gatesAsked: true }, source: 'fake', at: '2026-10-02T00:00:00.000Z' };
const start = { jobId: 'j1', laneId: 'm/lane-1', machineId: 'm', effectivePriority: 50, reason: 'idle lane' };
const lanePlan = { machineId: 'm', current: 0, target: 1, open: 1, close: [], drain: [], reason: 'work waiting' };

export const EVENT_EXAMPLES: Record<EventType, Record<string, unknown>> = {
  'job.queued': { spec: { executor: 'test', payload: { op: 'echo' }, priority: 60, goal: 'g' }, priority: 60, source: { source: 'github', kind: 'github', key: 'https://x/1', number: 1 } },
  'job.prioritized': { advice, statusAtAdvice: 'queued' },
  'job.held': { reason: 'budget' },
  'job.approved': {},
  'job.claimed': { attempts: 1, effectivePriority: 50, reason: 'idle lane' },
  'job.started': { attempts: 1 },
  'job.progressed': { progress: 0.5, message: 'half' },
  'job.finished': { result: { ok: true } },
  'job.failed': { error: 'boom' },
  'job.cancelled': { reason: 'cancelled while queued' },
  'job.requeued': { from: 'waiting_answer', reason: 'answered' },
  'job.parked': { from: 'waiting_answer', machineId: 'laptop', auto: true, why: 'Parked automatically: the question waited 30 min.' },
  'job.unparked': { to: 'queued' },
  'job.continued': { handoffId: 'h1' },
  'job.reattached': { reason: 'daemon restart' },
  'job.reprioritized': { from: 50, to: 80, reason: 'project:Priority=P1' },
  'job.respecified': { from: { executor: 'herdr-claude', cwd: '~/code/app' }, to: { executor: 'herdr-claude', model: 'claude-opus-5-5', cwd: '~/code/app-win', machineId: 'win-native', rule: 'windows' } },
  'lane.opened': {},
  'lane.closed': { reason: 'drained' },
  'decision.made': { decisionId: 'd1', trigger: 'tick', starts: [start], holds: [{ jobId: 'j2', reason: 'full' }], waits: [{ jobId: 'j3', reason: 'waiting for a lane: machine local\'s lane cap is 4, all 4 in use' }], lanes: [lanePlan], divergences: [{ jobId: 'j1', advice: 'ask_human', native: 'start', withAdvice: 'hold', note: 'n' }] },
  'question.asked': { questionId: 'q1', text: 'which?', detectedBy: 'marker', raisedBy: { machineId: 'desk', name: 'Desk tower', laneId: 'desk/lane-1' } },
  'question.escalated': { questionId: 'q1', target: 'human', reason: 'asked', text: 'which?', jobId: 'j1', goal: 'g', answerUrl: 'http://127.0.0.1/q', notifyCount: 0, renotify: true },
  'question.escalated_to_human': { questionId: 'q1', reason: 'fable: the owner\'s call', text: 'which?', jobId: 'j1', goal: 'g', answerUrl: 'http://127.0.0.1/q', notifyCount: 1, raisedBy: { machineId: 'desk', name: 'Desk tower', laneId: 'desk/lane-1' }, priority: 75, high: true },
  'question.answered': { questionId: 'q1', by: 'human', answer: 'yes' },
  'question.corrected': { questionId: 'q1', level: 'level-1', was: 'use postgres', answer: 'use sqlite', by: 'admin' },
  'question.closed': { questionId: 'q1', answer: 'The owner closed this question without answering. Continue on your own judgement; if you cannot, end with HOPPER_FAILED and say why.' },
  'question.dismissed': { questionId: 'q1' },
  'question.expired': { questionId: 'q1', after_ms: 1000 },
  'question.lapsed': { questionId: 'q1', lapsesAt: '2026-10-07T21:43:59.000Z' },
  'update.available': { from: 'a1b2c3d', to: 'e4f5a6b', ref: 'stable', changes: 3 },
  'update.started': { from: 'a1b2c3d', to: 'e4f5a6b', ref: 'stable' },
  'update.applied': { from: 'a1b2c3d', to: 'e4f5a6b', ref: 'stable' },
  'update.failed': { to: 'e4f5a6b', error: 'the new build does not load: SyntaxError' },
  'plugin.installed': { id: 'echo-executor', role: 'executor', commit: 'e4f5a6b' },
  'plugin.removed': { id: 'echo-executor' },
  'job.accepted': { by: 'pre-sort' },
  'job.rejected': { by: 'user', reason: 'rejected by the user' },
  'queue.ordered': { jobIds: ['j2', 'j1'] },
  'job.claimed_by_operator': {},
  'job.rerun': { by: 'user' },
  'job.dismissed': { by: 'user' },
  'job.work_kept': { paths: ['/home/me/hopper-jobs/.hopper-scratch/7d0c9b1e-2f4a-4c55-9e3b-1a2b3c4d5e6f/hopper'] },
  'job.work_removed': { paths: ['/home/me/hopper-jobs/.hopper-scratch/7d0c9b1e-2f4a-4c55-9e3b-1a2b3c4d5e6f'] },
  'job.cleanup_deferred': { error: 'herdr: client is not dialled in' },
  'job.cleaned_up': { deferredAt: '2026-10-07T21:31:00.000Z' },
  'job.unassigned': { assignee: 'octocat' },
  'job.reassigned': { assignee: 'octocat' },
  'source.stalled': { source: 'github-account', kind: 'github-account', error: 'GitHub is down', since: '2026-10-07T20:14:00.000Z' },
  'connected_account.expired': { provider: 'github', account: 'octocat', reason: 'GitHub refused the refresh token (bad_refresh_token)' },
  'connected_account.renewed': { provider: 'github', account: 'octocat', expiresAt: '2026-10-09T18:00:00.000Z' },
  'connected_account.renewal_failed': { provider: 'github', account: 'octocat', code: 'http_502' },
  'ui_session.ended': { reason: 'expired-idle', realm: 'corp' },
  'source.claim_released': { source: 'github-account', key: 'https://github.com/octocat/hello/issues/7', by: 'hopper', reason: 'claimed by this user of this hopper, with no job here' },
  'source.intake_migrated': { source: 'github-account', changes: [{ key: 'https://github.com/octocat/hello/issues/7', change: 'not assigned to you: assign it to you to take it' }] },
  'source.issues_assigned': { source: 'github-account', keys: ['https://github.com/octocat/hello/issues/7'], assignee: 'octocat' },
  'auth.pending': { loginId: 'l1', kind: 'device_code', tool: 'gh', expiresAt: '2026-10-08T18:15:00.000Z', run: 'herdr-claude' },
  'auth.completed': { loginId: 'l1', kind: 'device_code', tool: 'gh' },
  'auth.expired': { loginId: 'l1', kind: 'device_code', tool: 'gh', expiresAt: '2026-10-08T18:15:00.000Z' },
  'auth.cancelled': { loginId: 'l1', kind: 'device_code', tool: 'gh', by: 'user' },
  'auth.failed': { loginId: 'l1', kind: 'device_code', tool: 'gh', reason: 'the job ended: timed out' },
  'job.assessed': {
    recordId: 'f1', signature: '3f9c2a1b7d4e', class: 'shared', decision: 'redirect', reasons: ['known cause: Disk full', 'redirected: the job may run on another machine than desk'],
    summary: 'Redirected: Disk full on desk. Ran 1 time on desk. Failed: write: ENOSPC: no space left on device.', attempt: 1, auto: true, causeId: 'disk-full', problemId: 'p1',
  },
  'failure.grouped': { problemId: 'p1', signature: '3f9c2a1b7d4e', title: 'Disk full on desk', opened: true, general: false, decision: 'redirect', scope: { machineId: 'desk' }, affected: 1 },
  'failure.resolved': { problemId: 'p1', title: 'Disk full on desk', by: 'check', released: 2 },
  'failure.released': { problemId: 'p1', title: 'Disk full on desk', released: 2, person: 'operator CLI', via: 'cli' },
  'handoff.opened': {
    handoffId: 'h1', reason: 'retry_limit', summary: 'Needs a person. Ran 4 times on desk, the last for 2 min. Failed: read ECONNRESET.', notify: true,
    recordId: 'f1', decision: 'person', class: 'transient',
  },
  'handoff.closed': { handoffId: 'h1', end: 'run_again', nextJobId: 'j2', resolution: 'fixed' },
  'handoff.checked': { handoffId: 'h1', item: 'open', pullRequests: 1, shipped: true },
  'proposal.asked': { by: 'user' },
  'proposal.submitted': { proposalId: 'p1', version: 1, goal: 'Cache the board renders', missing: ['effort'], raisedBy: { machineId: 'desk', name: 'Desk tower', laneId: 'desk/lane-1' }, priority: 50, high: false },
  'proposal.escalated': { proposalId: 'p1', version: 1, target: 'opus', reason: 'submitted', goal: 'Cache the board renders' },
  'proposal.escalated_to_human': { proposalId: 'p1', version: 1, reason: 'fable approved: sound and small', priority: 80, high: true },
  'proposal.reviewed': { proposalId: 'p1', version: 1, stage: 'opus', verdict: 'request_changes', notes: 'Say how the cache is invalidated.' },
  'proposal.revision_requested': { proposalId: 'p1', version: 1, stage: 'opus', decision: 'request_changes', notes: 'Say how the cache is invalidated.' },
  'proposal.accepted': { proposalId: 'p1', version: 2, stage: 'human', by: 'owner', notes: 'Go ahead.' },
  'proposal.rejected': { proposalId: 'p1', version: 2, stage: 'human', by: 'owner', notes: 'Not worth the effort now.' },
  'proposal.cancelled': { proposalId: 'p1', version: 1, reason: 'its job is cancelled' },
  'research.asked': { by: 'user' },
  'research.submitted': { researchId: 'r1', version: 1, question: 'What can each machine reach?', missing: ['confidence'], raisedBy: { machineId: 'desk', name: 'Desk tower', laneId: 'desk/lane-1' }, priority: 50, high: false },
  'research.escalated': { researchId: 'r1', version: 1, target: 'human', reason: 'no reviewer levels configured', question: 'What can each machine reach?' },
  'research.escalated_to_human': { researchId: 'r1', version: 1, reason: 'no reviewer levels configured', priority: 80, high: true },
  'research.reviewed': { researchId: 'r1', version: 1, stage: 'opus', verdict: 'approve', notes: 'The findings follow from the sources.' },
  'research.revision_requested': { researchId: 'r1', version: 1, stage: 'human', decision: 'steer', notes: 'Only the AWS side.', by: 'owner' },
  'research.accepted': { researchId: 'r1', version: 2, stage: 'human', by: 'owner', notes: 'Enough to propose.' },
  'research.cancelled': { researchId: 'r1', version: 1, reason: 'its job is cancelled' },
  'usage.limits_changed': { from: { soft: 0.7, hard: 0.95 }, to: { soft: 0.6, hard: 0.9 } },
  'priority_lanes.changed': { from: [], to: ['desk/lane-1'], by: 'reliability' },
  'priority_lanes.settings_changed': {
    from: { highPriority: 75, count: 1, whenIdle: 'keep-free', windowDays: 14, minRuns: 5 },
    to: { highPriority: 75, count: 2, whenIdle: 'share', windowDays: 14, minRuns: 5 },
  },
  'machine.discovered': { machineId: 'desk', level: 'high', changes: { first: false, added: ['aws prod-deploy', 'credential file kubeconfig'], removed: [], level: { from: 'medium', to: 'high' } } },
  'machine.discovery_failed': { machineId: 'desk', error: 'the discovery on desk did not finish (exit 255): ssh: connect to host timed out' },
  'machine.radius_grew': { machineId: 'desk', from: 'medium', to: 'high' },
  'machine.actor_mismatch': { machineId: 'deploy-box', expected: 'high', found: 'medium' },
  'blast_radius.settings_changed': {
    from: { gateAt: 'high', pass: { labels: [], repos: [] }, rules: { prodPatterns: ['prod', 'production', 'prd'], prodAccounts: [], unconfirmed: 'write' }, actors: [], everyMinutes: 60 },
    to: { gateAt: 'high', pass: { labels: ['hopper:actor'], repos: [] }, rules: { prodPatterns: ['prod', 'production', 'prd'], prodAccounts: [], unconfirmed: 'write' }, actors: [{ machineId: 'deploy-box', purpose: 'production deploys', expected: 'high' }], everyMinutes: 60 },
  },
  'job.phase_changed': { from: 'work', to: 'research', reason: 'research only the auth part', mode: 'switch', questionId: 'q1', note: 'research only the auth part', by: 'owner' },
  'job.forked': { forkId: 'j2', to: 'research', mode: 'fork', questionId: 'q1', note: 'only the token lifetime', by: 'owner', parent: 'waiting', priority: 50, high: false },
  'job.fork_resolved': { forkId: 'j2', kind: 'research', questionId: 'q1', decision: 'accept', delivered: true, question: 'open' },
  'job.pull_request_merged': { pullRequest: 'https://github.com/owner/repo/pull/12', part: false },
  'job.pull_request_closed': { pullRequest: 'https://github.com/owner/repo/pull/13', part: true },
  'job.finish_briefed': { pullRequest: 'https://github.com/owner/repo/pull/14', step: 'rebase' },
  'yolo_mode.changed': { from: { on: false, repos: {} }, to: { on: false, repos: { 'owner/repo': true } }, by: 'owner' },
  'auto_answer.settings_changed': { from: { enabled: true, threshold: 'high' }, to: { enabled: true, threshold: 'medium' }, by: 'admin' },
  'auto_park.settings_changed': { from: { minutes: 30, highPriorityMinutes: 30 }, to: { minutes: 30, highPriorityMinutes: 10 }, by: 'admin' },
  'phase_shifts.settings_changed': { from: { defaultMode: 'fork', forkParent: 'wait', levels: [] }, to: { defaultMode: 'switch', forkParent: 'wait', levels: ['opus'] } },
  'job.gate_passed': { reason: 'held at the blast-radius gate: desk is rated high; only a job let through the gate runs there' },
  'minor_decision.picked': {
    pickId: 'p1', point: 'question-answer', by: 'jev', options: [{ id: '1', label: 'Yes, proceed' }, { id: '2', label: 'No' }],
    pick: '1', confidence: 0.91, mode: 'shadow', threshold: 0.85, applied: false, notApplied: 'shadow', questionId: 'q1',
  },
  'minor_decision.compared': { pickId: 'p1', point: 'question-answer', pick: '1', actual: '1', agreed: true, decidedBy: 'level-1' },
  'minor_decision.overridden': { pickId: 'p1', point: 'failure-assessment', pick: 'retry', actual: 'person' },
  'minor_decision.settings_changed': { point: 'question-answer', from: { mode: 'shadow', threshold: 0.85 }, to: { mode: 'active', threshold: 0.9 } },
  'queue.gate_changed': { from: { mode: 'auto-accept', autoAcceptPerHour: null }, to: { mode: 'review', autoAcceptPerHour: null } },
  'github_proxy.done': { requestId: 'r1', machine: 'desk', own: true, op: 'issue.create', repo: 'octo/tools', number: 42, url: 'https://github.com/octo/tools/issues/42' },
  'github_proxy.refused': { requestId: 'r2', machine: 'box', own: false, forUser: 'u2', job: 'j7', op: 'issue.comment', repo: 'octo/tools', reason: 'a job of another user may only file an issue through the hopper (issue.create), not issue.comment' },
  'github_proxy.failed': { requestId: 'r3', machine: 'desk', own: true, op: 'pr.create', repo: 'octo/tools', error: 'GitHub answered 422 to pr.create on octo/tools: Validation Failed (No commits between dev and fix)' },
  'vault.secret_set': { name: 'KUBE_TOKEN', by: 'Ada', replaced: false },
  'vault.secret_removed': { name: 'KUBE_TOKEN', by: 'Ada' },
  'template.saved': { template: 'kube', image: 'localhost/box-kubectl:1', secrets: ['KUBE_TOKEN'], profiles: [{ operation: 'read', asset: { kind: 'cluster', name: 'lab' } }], by: 'Ada' },
  'template.removed': { template: 'kube', by: 'Ada' },
  'vault.approved': { template: 'kube', image: 'localhost/box-kubectl:1', secrets: ['KUBE_TOKEN'], by: 'Ada' },
  'vault.revoked': { template: 'kube', by: 'Ada' },
  'template.profile_approved': { template: 'kube', operation: 'write', asset: { kind: 'cluster', name: 'lab' }, level: 'high', by: 'Ada' },
  'vault.delivered': { name: 'KUBE_TOKEN', template: 'kube', machine: 'hopper-sandbox-kube', job: 'f3b1c2d4-0000-4000-8000-000000000001' },
  'vault.minted': {
    kind: 'kube', operation: 'read', asset: { kind: 'namespace', name: 'lab/web' }, template: 'kube', machine: 'hopper-sandbox-kube', job: 'f3b1c2d4-0000-4000-8000-000000000001',
    credential: 'KUBE_LAB', decision: '6c1d2e3f-0000-4000-8000-000000000002', expiresAt: '2026-10-09T12:10:00.000Z', renewal: false,
  },
  'vault.mint_refused': {
    mint: { kind: 'kube', operation: 'write', asset: { kind: 'namespace', name: 'lab/web' } }, machine: 'hopper-sandbox-kube', template: 'kube', job: 'f3b1c2d4-0000-4000-8000-000000000001',
    reason: 'Access denied it: template kube is not approved to write on namespace lab/web. write on namespace lab/web waits for a person\'s approval on Settings → Vault (the first-time gate)',
    decision: '6c1d2e3f-0000-4000-8000-000000000003',
  },
  'vault.refused': { name: 'PROD_KEY', machine: 'hopper-sandbox-kube', template: 'kube', job: 'f3b1c2d4-0000-4000-8000-000000000001', reason: 'kube is not approved for PROD_KEY: a person adds it to the template and approves it' },
  'vault.credential_asked': { request: 'c9d0e1f2-0000-4000-8000-000000000583', skill: 'example-api', template: 'web', machine: 'hopper-sandbox-web', job: 'f3b1c2d4-0000-4000-8000-000000000001', why: 'deploy the web service' },
  'vault.credential_given': { request: 'c9d0e1f2-0000-4000-8000-000000000583', skill: 'example-api', name: 'example-api', kind: 'asked', template: 'web', by: 'github:octocat', approved: true, jobs: ['f3b1c2d4-0000-4000-8000-000000000001'] },
  'vault.credential_declined': { request: 'c9d0e1f2-0000-4000-8000-000000000583', skill: 'example-api', template: 'web', reason: 'deploy by hand this time', by: 'github:octocat', jobs: ['f3b1c2d4-0000-4000-8000-000000000001'] },
  'skill.listed': { requestId: 'r4', machine: 'hopper-sandbox-kube', template: 'kube' },
  'skill.loaded': { requestId: 'r5', machine: 'hopper-sandbox-kube', template: 'kube', skill: 'kube-diagnostics', asset: 'cluster/prod', decision: 'd1' },
  'skill.refused': { requestId: 'r6', machine: 'desk', skill: 'example-api', reason: 'the hopper has no skill example-api. It has: github, kube-diagnostics, aws-diagnostics, artifacts. For another service, say what credential it takes: sh "$HOPPER_SKILL" example-api --credential "<what it takes>". Else find another way.' },
  'artifact.created': { artifact: 'a1b2c3d4-0000-4000-8000-000000000624', title: 'Queue wait by hour', name: 'chart.html', type: 'text/html', size: 18432, sha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', issue: 'https://github.com/octo-org/hello/issues/7' },
  'artifact.shared': { artifact: 'a1b2c3d4-0000-4000-8000-000000000624', share: 's1', with: 'link', expiresAt: '2026-10-11T12:00:00.000Z', by: 'github:octocat' },
  'artifact.share_revoked': { artifact: 'a1b2c3d4-0000-4000-8000-000000000624', share: 's1', with: 'link', by: 'github:octocat' },
  'artifact.removed': { artifact: 'a1b2c3d4-0000-4000-8000-000000000624', reason: 'retention' },
  'artifact.settings_changed': {
    from: { maxBytes: 10485760, userBytes: 524288000, retentionDays: 30, publicLinks: true, linkHours: 24, linkHoursMax: 168 },
    to: { maxBytes: 10485760, userBytes: 524288000, retentionDays: 30, publicLinks: false, linkHours: 24, linkHoursMax: 168 }, by: 'github:octocat',
  },
};
